version: 2
project_name: go-asteroids

before:
  hooks:
    - apt-get update && apt-get install -y libx11-dev libgl1-mesa=dev libxcursor-dev libxi-dev
    - go mod tidy

builds:
  - id: asteroids
    binary: asteroids
    goos:
      - linux
      - windows
    goarch:
      - amd64

  - id: asteroids-wasm
    binary: asteroids
    goos:
      - js
    goarch:
      - wasm
    env:
      - CGO_ENABLED=1

archives:
  - formats:
      - binary
    name_template: >-
      asteroids_{{- tolower .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  use: github-native
